Repository exercism/java, pull requests merged in 2022-10, with the labels that each got.

#2173 Remove stale bot
  .github/workflows/stale.yml
Labels: hacktoberfest-accepted, x:rep/small

#2172 Convert exception assertions to AssertJ in SeriestTest
  exercises/practice/series/src/test/java/SeriesTest.java
Labels: hacktoberfest-accepted, x:rep/small

#2174 Convert exception assertions to AssertJ in 2 Exercises
  exercises/practice/change/src/test/java/ChangeCalculatorTest.java
  exercises/practice/collatz-conjecture/src/test/java/CollatzCalculatorTest.java
Labels: x:rep/tiny

#2176 Convert exception assertions to AssertJ in 2 Exercises
  exercises/practice/dominoes/src/test/java/DominoesTest.java
  exercises/practice/variable-length-quantity/src/test/java/VariableLengthQuantityTest.java
Labels: hacktoberfest-accepted, x:rep/tiny

#2178 2447 assertJ haming
  exercises/practice/hamming/src/test/java/HammingTest.java
Labels: hacktoberfest-accepted, x:rep/tiny

#2181 2447 assertJ FootballMatchReportsTest.java
  exercises/concept/football-match-reports/src/test/java/FootballMatchReportsTest.java
Labels: hacktoberfest-accepted, x:rep/tiny

#2183 Doubly linked list
  exercises/practice/linked-list/src/main/java/DoublyLinkedList.java
Labels: hacktoberfest-accepted, x:rep/small

#2185 Add Configlet badge to README
  README.md
Labels: hacktoberfest-accepted, x:rep/tiny

#2186 Convert exception assertions to AssertJ in 2 Exercises
  exercises/practice/tree-building/src/test/java/BuildTreeTest.java
  exercises/practice/wordy/src/test/java/WordProblemSolverTest.java
Labels: hacktoberfest-accepted, x:rep/tiny

#2190 Remove reference to Gitter
  CONTRIBUTING.md
  README.md
  docs/TESTS.md
  exercises/practice/hello-world/.docs/instructions.append.md
  exercises/shared/.docs/tests.md
Labels: hacktoberfest-accepted, x:rep/small

#2192 Add stubs to practice exercises S to V
  exercises/practice/satellite/src/main/java/Satellite.java
  exercises/practice/series/src/main/java/Series.java
  exercises/practice/sgf-parsing/src/main/java/SgfParsing.java
  exercises/practice/simple-cipher/src/main/java/Cipher.java
  exercises/practice/simple-linked-list/src/main/java/SimpleLinkedList.java
  exercises/practice/spiral-matrix/src/main/java/SpiralMatrixBuilder.java
  exercises/practice/sublist/src/main/java/RelationshipComputer.java
  exercises/practice/tournament/src/main/java/Tournament.java
  exercises/practice/transpose/src/main/java/Transpose.java
  exercises/practice/two-bucket/src/main/java/TwoBucket.java
Labels: hacktoberfest-accepted, x:rep/medium

#2191 Make Signal class visible in online editor
  exercises/practice/secret-handshake/.meta/config.json
Labels: hacktoberfest-accepted, x:rep/small

#2193 Convert exception assertions to AssertJ in NaturalNumberTest
  exercises/practice/perfect-numbers/src/test/java/NaturalNumberTest.java
Labels: hacktoberfest-accepted, x:rep/tiny
