Repository exercism/java, pull requests merged in 2022-07, with the labels that each got.

#2132 Confusing Exception name
  exercises/concept/cars-assemble/src/main/java/CarsAssemble.java
Labels: x:size/tiny

#2131 Squeaqy clean test
  exercises/concept/squeaky-clean/.meta/src/reference/java/SqueakyClean.java
  exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java
Labels: x:size/small

#2136 remove duplicate the
  docs/INSTALLATION.md
  exercises/concept/wizards-and-warriors/.docs/hints.md
Labels: x:rep/small

#2138 Fixed the url 404 not found for tutorial.md and changed the name
  POLICIES.md
  docs/TESTS.md
  exercises/practice/armstrong-numbers/.docs/instructions.append.md
  exercises/practice/leap/.docs/instructions.append.md
  exercises/practice/rna-transcription/.docs/instructions.append.md
  exercises/practice/two-fer/.docs/instructions.append.md
  exercises/shared/.docs/tests.md
Labels: x:rep/small

#2135 2114/hello world readme
  exercises/practice/hello-world/.docs/instructions.append.md
Labels: x:rep/small

#2141 Fix rename the url path for "master" to "main" and check the URLs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  POLICIES.md
  README.md
  exercises/practice/flatten-array/.meta/hints.md
  exercises/practice/hello-world/.docs/instructions.append.md
  reference/exercise-concepts/gigasecond.md
  reference/exercise-concepts/leap.md
  reference/exercise-concepts/matrix.md
  reference/exercise-concepts/rna-transcription.md
  scripts/create_issues_new_exercise.sh
  scripts/create_issues_versionchange_canonical.sh
Labels: x:rep/small

#2146 Update DartsTest.java for typos Where "Circle" was written as "Cirlce"
  exercises/practice/darts/src/test/java/DartsTest.java
Labels: x:rep/small

#2149 Update NeedForSpeed.java
  exercises/concept/need-for-speed/.meta/src/reference/java/NeedForSpeed.java
Labels: x:rep/small

#2150 Update hints.md
  exercises/concept/log-levels/.docs/hints.md
Labels: x:rep/small
