Repository exercism/java, pull requests merged in 2022-08, with the labels that each got.

#2152 Pin actions to SHAs
  .github/workflows/stale.yml
Labels: x:rep/tiny

#2142 Implement sgf-parsing practice exercise
  config.json
  exercises/practice/sgf-parsing/.docs/instructions.md
  exercises/practice/sgf-parsing/.meta/config.json
  exercises/practice/sgf-parsing/.meta/src/reference/java/SgfNode.java
  exercises/practice/sgf-parsing/.meta/src/reference/java/SgfParsing.java
  exercises/practice/sgf-parsing/.meta/src/reference/java/SgfParsingException.java
  exercises/practice/sgf-parsing/.meta/tests.toml
  exercises/practice/sgf-parsing/build.gradle
  exercises/practice/sgf-parsing/src/main/java/SgfNode.java
  exercises/practice/sgf-parsing/src/main/java/SgfParsing.java
  exercises/practice/sgf-parsing/src/main/java/SgfParsingException.java
  exercises/practice/sgf-parsing/src/test/java/SgfParsingTest.java
  exercises/settings.gradle
Labels: x:rep/large

#2153 removed the reference to UnsupportedOperationException in instructions
  exercises/practice/hello-world/.docs/instructions.append.md
Labels: x:rep/small

#2154 Update PythagoreanTripletTest.java
  exercises/practice/pythagorean-triplet/src/test/java/PythagoreanTripletTest.java
Labels: x:rep/small
