Repository exercism/java, pull requests merged in 2023-11, with the labels that each got.

#2547 pop-count: update metadata
  config.json
  exercises/practice/pop-count/.meta/config.json
Labels: x:size/tiny

#2355 Add MazeGenerator exercise and related tests
  config.json
  exercises/practice/mazy-mice/.docs/hints.md
  exercises/practice/mazy-mice/.docs/instructions.md
  exercises/practice/mazy-mice/.docs/introduction.md
  exercises/practice/mazy-mice/.meta/config.json
  exercises/practice/mazy-mice/.meta/src/reference/java/Dimensions.java
  exercises/practice/mazy-mice/.meta/src/reference/java/MazeGenerator.java
  exercises/practice/mazy-mice/build.gradle
  exercises/practice/mazy-mice/src/main/java/MazeGenerator.java
  exercises/practice/mazy-mice/src/test/java/MazeGeneratorTest.java
  exercises/settings.gradle
Labels: x:size/large

#2545 Remove nested test classes from practice exercise simple-cipher (#2538)
  exercises/practice/simple-cipher/src/test/java/SimpleCipherTest.java
Labels: x:size/small

#2558 lens-person: forgo exercise
  config.json
Labels: x:size/tiny

#2559 Run tests using java-test-runner
  .github/workflows/gradle.yml
  .github/workflows/test.yml
  bin/test-with-test-runner
  exercises/practice/bowling/.meta/config.json
  exercises/practice/error-handling/.meta/config.json
  exercises/practice/forth/.meta/config.json
  exercises/practice/hangman/.meta/config.json
  exercises/practice/mazy-mice/.meta/src/reference/java/MazeGenerator.java
  exercises/practice/mazy-mice/src/test/java/MazeGeneratorTest.java
  exercises/practice/ocr-numbers/.meta/config.json
  exercises/practice/poker/.meta/config.json
  exercises/practice/queen-attack/.meta/config.json
  exercises/practice/rest-api/.meta/config.json
  exercises/practice/spiral-matrix/.meta/config.json
  exercises/practice/tournament/.meta/config.json
Labels: ci

#2560 Update status badges on README.md
  README.md
Labels: x:size/tiny

#2568 Sync tests for practice exercise `hamming`
  exercises/practice/hamming/.approaches/for-loop/content.md
  exercises/practice/hamming/.approaches/introduction.md
  exercises/practice/hamming/.approaches/intstream-filter-count/content.md
  exercises/practice/hamming/.approaches/intstream-map-sum/content.md
  exercises/practice/hamming/.approaches/intstream-reduce/content.md
  exercises/practice/hamming/.docs/instructions.append.md
  exercises/practice/hamming/.meta/src/reference/java/Hamming.java
  exercises/practice/hamming/.meta/tests.toml
  exercises/practice/hamming/.meta/version
  exercises/practice/hamming/src/test/java/HammingTest.java
Labels: x:size/small

#2567 Sync tests for practice exercise `gigasecond`
  exercises/practice/gigasecond/.meta/tests.toml
  exercises/practice/gigasecond/.meta/version
  exercises/practice/gigasecond/src/test/java/GigasecondTest.java
Labels: x:size/small

#2572 Sync tests for practice exercise `largest-series-product`
  exercises/practice/largest-series-product/.meta/tests.toml
  exercises/practice/largest-series-product/.meta/version
Labels: x:size/small

#2570 Sync tests for practice exercise `isogram`
  exercises/practice/isogram/.meta/tests.toml
  exercises/practice/isogram/.meta/version
  exercises/practice/isogram/src/test/java/IsogramCheckerTest.java
Labels: x:size/small

#2569 Sync tests for practice exercise `isbn-verifier`
  exercises/practice/isbn-verifier/.meta/tests.toml
  exercises/practice/isbn-verifier/.meta/version
  exercises/practice/isbn-verifier/src/test/java/IsbnVerifierTest.java
Labels: x:size/small

#2571 Sync tests for practice exercise `kindergarten-garden`
  exercises/practice/kindergarten-garden/.meta/tests.toml
  exercises/practice/kindergarten-garden/.meta/version
  exercises/practice/kindergarten-garden/src/test/java/KindergartenGardenTest.java
Labels: x:size/small

#2584 Add nullability concept
  concepts/nullability/.meta/config.json
  concepts/nullability/about.md
  concepts/nullability/introduction.md
  concepts/nullability/links.json
  config.json
  exercises/concept/tim-from-marketing/.docs/hints.md
  exercises/concept/tim-from-marketing/.docs/instructions.md
  exercises/concept/tim-from-marketing/.docs/introduction.md
  exercises/concept/tim-from-marketing/.docs/introduction.md.tpl
  exercises/concept/tim-from-marketing/.meta/config.json
  exercises/concept/tim-from-marketing/.meta/design.md
  exercises/concept/tim-from-marketing/.meta/src/reference/java/Badge.java
  exercises/concept/tim-from-marketing/build.gradle
  exercises/concept/tim-from-marketing/src/main/java/Badge.java
  exercises/concept/tim-from-marketing/src/test/java/BadgeTest.java
  exercises/settings.gradle
Labels: x:size/large

#2581 Add missing prerequisites
  config.json
Labels: x:size/large

#2582 Add concept `randomness` and concept exercise `captains-log`
  concepts/randomness/.meta/config.json
  concepts/randomness/about.md
  concepts/randomness/introduction.md
  concepts/randomness/links.json
  config.json
  exercises/concept/captains-log/.docs/hints.md
  exercises/concept/captains-log/.docs/instructions.md
  exercises/concept/captains-log/.docs/introduction.md
  exercises/concept/captains-log/.docs/introduction.md.tpl
  exercises/concept/captains-log/.meta/config.json
  exercises/concept/captains-log/.meta/design.md
  exercises/concept/captains-log/.meta/src/reference/java/CaptainsLog.java
  exercises/concept/captains-log/build.gradle
  exercises/concept/captains-log/src/main/java/CaptainsLog.java
  exercises/concept/captains-log/src/test/java/CaptainsLogTest.java
  exercises/settings.gradle
Labels: x:size/large

#2585 Fixed typos
  concepts/inheritance/introduction.md
  exercises/concept/wizards-and-warriors/.docs/hints.md
  exercises/concept/wizards-and-warriors/.docs/introduction.md
  exercises/concept/wizards-and-warriors/.meta/src/reference/java/Fighter.java
Labels: x:size/tiny

#2587 Remove deprecated exercises from Gradle project
  exercises/settings.gradle
Labels: x:size/tiny
