Repository exercism/java, pull requests merged in 2023-06, with the labels that each got.

#2323 Fix typo in Introduction of Need for Speed
  exercises/concept/need-for-speed/.docs/introduction.md
Labels: x:rep/tiny

#2322 Update the Introduction of Football Match Reports
  exercises/concept/football-match-reports/.docs/introduction.md
Labels: x:rep/small

#2321 Update HighScoresTest.java
  exercises/practice/high-scores/src/test/java/HighScoresTest.java
Labels: x:rep/medium
