Repository exercism/java, pull requests merged in 2023-10, with the labels that each got.

#2496 Add concept `enums` with concept exercise `logs-logs-logs`
  concepts/enums/.meta/config.json
  concepts/enums/about.md
  concepts/enums/introduction.md
  concepts/enums/links.json
  config.json
  exercises/concept/logs-logs-logs/.docs/hints.md
  exercises/concept/logs-logs-logs/.docs/instructions.md
  exercises/concept/logs-logs-logs/.docs/introduction.md
  exercises/concept/logs-logs-logs/.docs/introduction.md.tpl
  exercises/concept/logs-logs-logs/.meta/config.json
  exercises/concept/logs-logs-logs/.meta/design.md
  exercises/concept/logs-logs-logs/.meta/src/reference/java/LogLevel.java
  exercises/concept/logs-logs-logs/.meta/src/reference/java/LogLine.java
  exercises/concept/logs-logs-logs/build.gradle
  exercises/concept/logs-logs-logs/src/main/java/LogLevel.java
  exercises/concept/logs-logs-logs/src/main/java/LogLine.java
  exercises/concept/logs-logs-logs/src/test/java/LogsLogsLogsTest.java
  exercises/settings.gradle
Labels: x:size/large

#2509 Update change calculator test to use assertj (#2147)
  exercises/practice/change/src/test/java/ChangeCalculatorTest.java
Labels: x:size/small

#2510 Update tests to use assertj (#2147)
  exercises/practice/collatz-conjecture/src/test/java/CollatzCalculatorTest.java
  exercises/practice/crypto-square/src/test/java/CryptoSquareTest.java
  exercises/practice/darts/src/test/java/DartsTest.java
  exercises/practice/difference-of-squares/src/test/java/DifferenceOfSquaresCalculatorTest.java
  exercises/practice/dnd-character/src/test/java/DnDCharacterTest.java
  exercises/practice/dominoes/src/test/java/DominoesTest.java
  exercises/practice/protein-translation/src/test/java/ProteinTranslatorTest.java
  exercises/practice/rotational-cipher/src/test/java/RotationalCipherTest.java
Labels: x:size/small

#2514 Remove outdated instructions from practice exercises
  exercises/practice/bob/.docs/instructions.append.md
  exercises/practice/flatten-array/.docs/instructions.append.md
  exercises/practice/flatten-array/.meta/hints.md
  exercises/practice/grep/.docs/instructions.append.md
  exercises/practice/matching-brackets/.docs/instructions.append.md
  exercises/practice/nucleotide-count/.docs/instructions.append.md
  exercises/practice/pascals-triangle/.docs/instructions.append.md
  exercises/practice/phone-number/.docs/instructions.append.md
  exercises/practice/pig-latin/.docs/instructions.append.md
  exercises/practice/prime-factors/.docs/instructions.append.md
  exercises/practice/robot-name/.docs/instructions.append.md
  exercises/practice/run-length-encoding/.docs/instructions.append.md
  exercises/practice/series/.docs/instructions.append.md
  exercises/practice/word-count/.docs/instructions.append.md
Labels: x:size/tiny

#2515 Use AssertJ for the remaining exercises
  exercises/practice/grade-school/src/test/java/SchoolTest.java
  exercises/practice/tree-building/src/test/java/BuildTreeTest.java
  exercises/practice/zipper/src/test/java/ZipperTest.java
Labels: x:size/small

#2519 Fix comment in "Need for speed"
  exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
Labels: x:size/tiny

#2521 Update CarsAssembleTest.java
  exercises/concept/cars-assemble/src/test/java/CarsAssembleTest.java
Labels: x:size/small

#2524 Quick fix variable type in the description
  exercises/practice/hamming/.approaches/intstream-reduce/content.md
Labels: x:size/tiny

#2525 Check formatting using Configlet in CI
  .github/workflows/configlet.yml
  config.json
  exercises/concept/logs-logs-logs/.meta/config.json
  exercises/practice/bob/.approaches/config.json
  exercises/practice/collatz-conjecture/.approaches/config.json
  exercises/practice/darts/.approaches/config.json
  exercises/practice/difference-of-squares/.approaches/config.json
  exercises/practice/grains/.approaches/config.json
  exercises/practice/hamming/.approaches/config.json
  exercises/practice/isbn-verifier/.approaches/config.json
  exercises/practice/isogram/.approaches/config.json
  exercises/practice/leap/.approaches/config.json
  exercises/practice/pangram/.approaches/config.json
  exercises/practice/pig-latin/.approaches/config.json
  exercises/practice/pov/.meta/config.json
  exercises/practice/pythagorean-triplet/.approaches/config.json
  exercises/practice/raindrops/.approaches/config.json
  exercises/practice/robot-name/.approaches/config.json
  exercises/practice/scrabble-score/.approaches/config.json
  exercises/practice/secret-handshake/.approaches/config.json
  exercises/practice/square-root/.meta/config.json
Labels: ci

#2526 Sync practice exercise docs + filepaths
  exercises/practice/bottle-song/.meta/config.json
  exercises/practice/high-scores/.meta/config.json
  exercises/practice/meetup/.docs/instructions.md
  exercises/practice/phone-number/.docs/instructions.md
  exercises/practice/sgf-parsing/.docs/instructions.md
Labels: x:size/small

#2541 Remove duplicate Gradle workflows being triggered
  .github/workflows/gradle.yml
Labels: ci, x:size/small

#2542 Fix table formatting in POLICIES.md
  POLICIES.md
Labels: documentation, x:size/small

#2544 Remove nested test classes from practice exercise rest-api
  exercises/practice/rest-api/src/test/java/RestApiTest.java
Labels: x:size/small
