Repository exercism/java, pull requests merged in 2023-02, with the labels that each got.

#2223 Convert exception assertions to AssertJ
  exercises/practice/satellite/src/test/java/SatelliteTest.java
Labels: x:rep/small

#2224 Convert exception assertions to AssertJ
  exercises/practice/grains/src/test/java/GrainsTest.java
Labels: x:rep/small

#2201 WIP: ledger: implement exercise
  config.json
  exercises/practice/ledger/.docs/instructions.md
  exercises/practice/ledger/.meta/config.json
  exercises/practice/ledger/.meta/src/reference/java/Ledger.java
  exercises/practice/ledger/build.gradle
  exercises/practice/ledger/src/main/java/Ledger.java
  exercises/practice/ledger/src/test/java/LedgerTest.java
  exercises/settings.gradle
Labels: x:rep/large

#2209 I have added in the separate three-domino-loops test to the DominoesT…
  exercises/practice/dominoes/src/test/java/DominoesTest.java
Labels: x:rep/small

#2213 update Darts.java score method signature to match test class parameter types
  exercises/practice/darts/src/main/java/Darts.java
Labels: x:rep/small

#2215 fixed typo in parameter identifier
  exercises/concept/remote-control-competition/.meta/src/reference/java/ProductionRemoteControlCar.java
  exercises/concept/remote-control-competition/src/main/java/ProductionRemoteControlCar.java
Labels: x:rep/small

#2216 fixed typo in test method name
  exercises/concept/remote-control-competition/src/test/java/RemoteControlCarTest.java
Labels: x:rep/tiny

#2218 Fix dnd character issues
  exercises/practice/dnd-character/.meta/src/reference/java/DnDCharacter.java
  exercises/practice/dnd-character/src/main/java/DnDCharacter.java
  exercises/practice/dnd-character/src/test/java/DnDCharacterTest.java
Labels: x:rep/medium

#2262 2261 exercise ledger fix unit tests
  exercises/practice/ledger/src/test/java/LedgerTest.java
Labels: x:rep/small

#2225 Update instructions for clarity on the setup.
  exercises/concept/remote-control-competition/.docs/instructions.md
Labels: x:rep/small

#2264 Add POV exercise
  config.json
  exercises/practice/pov/.docs/instructions.append.md
  exercises/practice/pov/.docs/instructions.md
  exercises/practice/pov/.meta/config.json
  exercises/practice/pov/.meta/src/reference/java/Tree.java
  exercises/practice/pov/.meta/tests.toml
  exercises/practice/pov/build.gradle
  exercises/practice/pov/src/main/java/Tree.java
  exercises/practice/pov/src/test/java/PovTest.java
  exercises/settings.gradle
Labels: x:rep/tiny

#2232 2133 stub for some exercises
  exercises/practice/accumulate/src/main/java/Accumulate.java
  exercises/practice/binary/src/main/java/Binary.java
  exercises/practice/hexadecimal/src/main/java/Hexadecimal.java
  exercises/practice/octal/src/main/java/Octal.java
  exercises/practice/strain/src/main/java/Strain.java
  exercises/practice/trinary/src/main/java/Trinary.java
Labels: x:rep/small

#2240 Fix typo in the Dig Deeper text for Grains
  exercises/practice/grains/.approaches/introduction.md
Labels: x:rep/tiny

#2260 Update checkstyle
  exercises/build.gradle
  exercises/checkstyle.xml
Labels: x:rep/small

#2265 2257 birds watcher remove test
  exercises/concept/bird-watcher/.meta/src/reference/java/BirdWatcher.java
  exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java
Labels: x:rep/small

#2268 Sync gigasecond docs with problem-specifications
  exercises/practice/gigasecond/.docs/instructions.md
  exercises/practice/gigasecond/.docs/introduction.md
Labels: x:rep/small
