Repository exercism/java, pull requests merged in 2023-09, with the labels that each got.

#2351 Remove '(static)' in default exception messages for non-static method…
  exercises/concept/elons-toy-car/src/main/java/ElonsToyCar.java
Labels: x:size/tiny

#2345 Add stubs to `allergies` exercise
  exercises/practice/allergies/src/main/java/Allergies.java
Labels: x:size/small

#2346 Add stubs to `forth` exercise
  exercises/practice/forth/src/main/java/ForthEvaluator.java
Labels: x:size/small

#2348 Remove non-existing concepts from config.json
  config.json
Labels: x:size/tiny

#2353 Update Rational.java
  exercises/practice/rational-numbers/src/main/java/Rational.java
Labels: x:size/tiny

#2308 Wizards and warriors: more generic param names for #damagePoints
  exercises/concept/wizards-and-warriors/src/main/java/Fighter.java
Labels: x:size/tiny

#2358 Deprecate `beer-song` and `diffie-hellman`
  config.json
Labels: x:size/small

#2369 Sync docs for practice exercise acronym
  exercises/practice/acronym/.docs/instructions.md
Labels: x:size/tiny

#2371 Sync docs for practice exercise all-your-base
  exercises/practice/all-your-base/.docs/instructions.md
Labels: x:size/tiny

#2372 Sync docs for practice exercise allergies
  exercises/practice/allergies/.docs/instructions.md
Labels: x:size/tiny

#2373 Sync docs for practice exercise alphametics
  exercises/practice/alphametics/.docs/instructions.md
Labels: x:size/tiny

#2375 Sync docs for practice exercise armstrong-numbers
  exercises/practice/armstrong-numbers/.docs/instructions.md
Labels: x:size/tiny

#2376 Sync docs for practice exercise atbash-cipher
  exercises/practice/atbash-cipher/.docs/instructions.md
Labels: x:size/tiny

#2377 Sync docs for practice exercise bank-account
  exercises/practice/bank-account/.docs/instructions.md
Labels: x:size/tiny

#2378 Sync docs for practice exercise binary-search
  exercises/practice/binary-search/.docs/instructions.md
Labels: x:size/tiny

#2379 Sync docs for practice exercise binary-search-tree
  exercises/practice/binary-search-tree/.docs/instructions.md
Labels: x:size/tiny

#2380 Sync docs for practice exercise book-store
  exercises/practice/book-store/.docs/instructions.md
Labels: x:size/tiny

#2381 Sync docs for practice exercise bowling
  exercises/practice/bowling/.docs/instructions.md
Labels: x:size/tiny

#2383 Sync docs for practice exercise clock
  exercises/practice/clock/.meta/config.json
Labels: x:size/tiny

#2384 Sync docs for practice exercise meetup
  exercises/practice/meetup/.meta/config.json
Labels: x:size/tiny

#2382 Sync docs for practice exercise binary-search-tree
  exercises/practice/binary-search-tree/.meta/config.json
Labels: x:size/tiny

#2385 Sync docs for practice exercise secret-handshake
  exercises/practice/secret-handshake/.meta/config.json
Labels: x:size/tiny

#2391 Sync docs for practice exercise zipper
  exercises/practice/zipper/.docs/instructions.md
Labels: x:size/tiny

#2392 Sync docs for practice exercise zebra-puzzle
  exercises/practice/zebra-puzzle/.docs/instructions.md
Labels: x:size/tiny

#2393 Sync docs for practice exercise yacht
  exercises/practice/yacht/.docs/instructions.md
Labels: x:size/tiny

#2394 Sync docs for practice exercise wordy
  exercises/practice/wordy/.docs/instructions.md
Labels: x:size/tiny

#2395 Sync docs for practice exercise word-search
  exercises/practice/word-search/.docs/instructions.md
Labels: x:size/tiny

#2396 Sync docs for practice exercise variable-length-quantity
  exercises/practice/variable-length-quantity/.docs/instructions.md
Labels: x:size/tiny

#2397 Sync docs for practice exercise two-fer
  exercises/practice/two-fer/.docs/instructions.md
Labels: x:size/tiny

#2399 Sync docs for practice exercise twelve-days
  exercises/practice/twelve-days/.docs/instructions.md
Labels: x:size/tiny

#2400 Sync docs for practice exercise triangle
  exercises/practice/triangle/.docs/instructions.md
Labels: x:size/tiny

#2390 Update calculator conundrum to use test runner v3 features
  exercises/concept/calculator-conundrum/build.gradle
  exercises/concept/calculator-conundrum/src/test/java/CalculatorConundrumTest.java
Labels: x:size/small

#2401 Sync docs for practice exercise sublist
  exercises/practice/sublist/.docs/instructions.md
Labels: x:size/tiny

#2402 Sync docs for practice exercise spiral-matrix
  exercises/practice/spiral-matrix/.docs/instructions.md
Labels: x:size/tiny

#2403 Sync docs for practice exercise space-age
  exercises/practice/space-age/.docs/instructions.md
Labels: x:size/tiny

#2404 Sync docs for practice exercise simple-linked-list
  exercises/practice/simple-linked-list/.docs/instructions.md
Labels: x:size/tiny

#2406 Sync docs for practice exercise series
  exercises/practice/series/.docs/instructions.md
Labels: x:size/tiny

#2407 Sync docs for practice exercise tree-building
  exercises/practice/tree-building/.docs/instructions.md
Labels: x:size/tiny

#2408 Sync docs for practice exercise change
  exercises/practice/change/.docs/instructions.md
Labels: x:size/tiny

#2409 Sync docs for practice exercise circular-buffer
  exercises/practice/circular-buffer/.docs/instructions.md
Labels: x:size/tiny

#2410 Sync docs for practice exercise collatz-conjecture
  exercises/practice/collatz-conjecture/.docs/instructions.md
Labels: x:size/tiny

#2411 Sync docs for practice exercise complex-numbers
  exercises/practice/complex-numbers/.docs/instructions.md
Labels: x:size/tiny

#2412 Sync docs for practice exercise connect
  exercises/practice/connect/.docs/instructions.md
Labels: x:size/tiny

#2414 Sync docs for practice exercise custom-set
  exercises/practice/custom-set/.docs/instructions.md
Labels: x:size/tiny

#2415 Test runner v3 bird watcher
  exercises/concept/bird-watcher/build.gradle
  exercises/concept/bird-watcher/src/test/java/BirdWatcherTest.java
Labels: x:size/small

#2426 Remove script which checks non-existing canonical versions
  scripts/canonical_data_check.sh
Labels: x:size/tiny

#2374 Sync docs for practice exercise anagram
  exercises/practice/anagram/.docs/instructions.md
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/src/test/java/AnagramTest.java
Labels: x:size/small

#2425 Sync docs for practice exercise transpose
  exercises/practice/transpose/.docs/instructions.md
Labels: x:size/tiny

#2424 Sync docs for practice exercise tournament
  exercises/practice/tournament/.docs/instructions.md
Labels: x:size/tiny

#2423 Sync docs for practice exercise secret-handshake
  exercises/practice/secret-handshake/.docs/instructions.md
Labels: x:size/tiny

#2422 Sync docs for practice exercise say
  exercises/practice/say/.docs/instructions.md
Labels: x:size/tiny

#2421 Sync docs for practice exercise satellite
  exercises/practice/satellite/.docs/instructions.md
Labels: x:size/tiny

#2420 Sync docs for practice exercise run-length-encoding
  exercises/practice/run-length-encoding/.docs/instructions.md
Labels: x:size/tiny

#2419 Sync docs for practice exercise rotational-cipher
  exercises/practice/rotational-cipher/.docs/instructions.md
Labels: x:size/tiny

#2418 Sync docs for practice exercise roman-numerals
  exercises/practice/roman-numerals/.docs/instructions.md
Labels: x:size/tiny

#2417 Sync docs for practice exercise robot-simulator
  exercises/practice/robot-simulator/.docs/instructions.md
Labels: x:size/tiny

#2416 Sync docs for practice exercise robot-name
  exercises/practice/robot-name/.docs/instructions.md
Labels: x:size/tiny

#2413 Sync docs for practice exercise crypto-square
  exercises/practice/crypto-square/.docs/instructions.md
Labels: x:size/tiny

#2405 Sync docs for practice exercise simple-cipher
  exercises/practice/simple-cipher/.docs/instructions.md
Labels: x:size/tiny

#2398 Sync docs for practice exercise two-bucket
  exercises/practice/two-bucket/.docs/instructions.md
Labels: x:size/tiny

#2428 Update cars assemble to use test runner v3 features
  exercises/concept/cars-assemble/build.gradle
  exercises/concept/cars-assemble/src/test/java/CarsAssembleTest.java
Labels: x:size/small

#2466 Sync docs for practice exercise hello-world
  exercises/practice/hello-world/.docs/instructions.md
Labels: x:size/tiny

#2465 Sync docs for practice exercise house
  exercises/practice/house/.docs/instructions.md
Labels: x:size/tiny

#2464 Sync docs for practice exercise isbn-verifier
  exercises/practice/isbn-verifier/.docs/instructions.md
Labels: x:size/tiny

#2463 Sync docs for practice exercise isogram
  exercises/practice/isogram/.docs/instructions.md
Labels: x:size/tiny

#2462 Sync docs for practice exercise kindergarten-garden
  exercises/practice/kindergarten-garden/.docs/instructions.md
Labels: x:size/tiny

#2461 Sync docs for practice exercise knapsack
  exercises/practice/knapsack/.docs/instructions.md
Labels: x:size/tiny

#2460 Sync docs for practice exercise leap
  exercises/practice/leap/.docs/instructions.md
Labels: x:size/tiny

#2459 Sync docs for practice exercise list-ops
  exercises/practice/list-ops/.docs/instructions.md
Labels: x:size/tiny

#2458 Sync docs for practice exercise luhn
  exercises/practice/luhn/.docs/instructions.md
Labels: x:size/tiny

#2457 Sync docs for practice exercise markdown
  exercises/practice/markdown/.docs/instructions.md
Labels: x:size/tiny

#2456 Sync docs for practice exercise matching-brackets
  exercises/practice/matching-brackets/.docs/instructions.md
Labels: x:size/tiny

#2455 Sync docs for practice exercise matrix
  exercises/practice/matrix/.docs/instructions.md
Labels: x:size/tiny

#2454 Sync docs for practice exercise micro-blog
  exercises/practice/micro-blog/.docs/instructions.md
Labels: x:size/tiny

#2453 Sync docs for practice exercise minesweeper
  exercises/practice/minesweeper/.docs/instructions.md
Labels: x:size/tiny

#2452 Sync docs for practice exercise nth-prime
  exercises/practice/nth-prime/.docs/instructions.md
Labels: x:size/tiny

#2451 Sync docs for practice exercise nucleotide-count
  exercises/practice/nucleotide-count/.docs/instructions.md
Labels: x:size/tiny

#2450 Sync docs for practice exercise ocr-numbers
  exercises/practice/ocr-numbers/.docs/instructions.md
Labels: x:size/tiny

#2449 Sync docs for practice exercise palindrome-products
  exercises/practice/palindrome-products/.docs/instructions.md
Labels: x:size/tiny

#2448 Sync docs for practice exercise pangram
  exercises/practice/pangram/.docs/instructions.md
Labels: x:size/tiny

#2447 Sync docs for practice exercise proverb
  exercises/practice/proverb/.docs/instructions.md
Labels: x:size/tiny

#2446 Sync docs for practice exercise protein-translation
  exercises/practice/protein-translation/.docs/instructions.md
Labels: x:size/tiny

#2445 Sync docs for practice exercise prime-factors
  exercises/practice/prime-factors/.docs/instructions.md
Labels: x:size/tiny

#2444 Sync docs for practice exercise poker
  exercises/practice/poker/.docs/instructions.md
Labels: x:size/tiny

#2443 Sync docs for practice exercise parallel-letter-frequency
  exercises/practice/parallel-letter-frequency/.docs/instructions.md
Labels: x:size/tiny

#2442 Sync docs for practice exercise pascals-triangle
  exercises/practice/pascals-triangle/.docs/instructions.md
Labels: x:size/tiny

#2441 Sync docs for practice exercise perfect-numbers
  exercises/practice/perfect-numbers/.docs/instructions.md
Labels: x:size/tiny

#2440 Sync docs for practice exercise phone-number
  exercises/practice/phone-number/.docs/instructions.md
Labels: x:size/tiny

#2439 Sync docs for practice exercise pig-latin
  exercises/practice/pig-latin/.docs/instructions.md
Labels: x:size/tiny

#2438 Sync docs for practice exercise pythagorean-triplet
  exercises/practice/pythagorean-triplet/.docs/instructions.md
Labels: x:size/tiny

#2437 Sync docs for practice exercise queen-attack
  exercises/practice/queen-attack/.docs/instructions.md
Labels: x:size/tiny

#2436 Sync docs for practice exercise rail-fence-cipher
  exercises/practice/rail-fence-cipher/.docs/instructions.md
Labels: x:size/tiny

#2435 Sync docs for practice exercise raindrops
  exercises/practice/raindrops/.docs/instructions.md
Labels: x:size/tiny

#2434 Sync docs for practice exercise rational-numbers
  exercises/practice/rational-numbers/.docs/instructions.md
Labels: x:size/tiny

#2433 Sync docs for practice exercise rectangles
  exercises/practice/rectangles/.docs/instructions.md
Labels: x:size/tiny

#2432 Sync docs for practice exercise resistor-color
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#2431 Sync docs for practice exercise resistor-color-duo
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny

#2430 Sync docs for practice exercise rest-api
  exercises/practice/rest-api/.docs/instructions.md
Labels: x:size/tiny

#2429 Sync docs for practice exercise rna-transcription
  exercises/practice/rna-transcription/.docs/instructions.md
  exercises/practice/rna-transcription/.docs/introduction.md
Labels: x:size/tiny

#2427 Update blackjack to use test runner v3 features
  exercises/concept/blackjack/build.gradle
  exercises/concept/blackjack/src/test/java/BlackjackTest.java
Labels: x:size/small

#2470 Sync docs for practice exercise darts
  exercises/practice/darts/.docs/instructions.md
Labels: x:size/tiny

#2471 Sync docs for practice exercise diamond
  exercises/practice/diamond/.docs/instructions.md
Labels: x:size/tiny

#2472 Sync docs for practice exercise difference-of-squares
  exercises/practice/difference-of-squares/.docs/instructions.md
Labels: x:size/tiny

#2473 Sync docs for practice exercise dnd-character
  exercises/practice/dnd-character/.docs/instructions.md
Labels: x:size/tiny

#2474 Sync docs for practice exercise dominoes
  exercises/practice/dominoes/.docs/instructions.md
Labels: x:size/tiny

#2475 Sync docs for practice exercise error-handling
  exercises/practice/error-handling/.docs/instructions.md
Labels: x:size/tiny

#2476 Sync docs for practice exercise etl
  exercises/practice/etl/.docs/instructions.md
Labels: x:size/tiny

#2477 Sync docs for practice exercise flatten-array
  exercises/practice/flatten-array/.docs/instructions.md
Labels: x:size/tiny

#2478 Sync docs for practice exercise food-chain
  exercises/practice/food-chain/.docs/instructions.md
Labels: x:size/tiny

#2479 Sync docs for practice exercise forth
  exercises/practice/forth/.docs/instructions.md
Labels: x:size/tiny

#2480 Sync docs for practice exercise grade-school
  exercises/practice/grade-school/.docs/instructions.md
Labels: x:size/tiny

#2481 Sync docs for practice exercise grains
  exercises/practice/grains/.docs/instructions.md
Labels: x:size/tiny

#2483 Sync docs for practice exercise hamming
  exercises/practice/hamming/.docs/instructions.md
Labels: x:size/tiny

#2484 Sync docs for practice exercise hangman
  exercises/practice/hangman/.docs/instructions.md
Labels: x:size/tiny

#2485 Sync docs for practice exercise go-counting
  exercises/practice/go-counting/.docs/instructions.md
Labels: x:size/tiny

#2482 Sync docs for practice exercise grep
  exercises/practice/grep/.docs/instructions.md
Labels: x:size/tiny

#2490 Update elons toy car to use test runner v3 features
  exercises/concept/elons-toy-car/build.gradle
  exercises/concept/elons-toy-car/src/test/java/ElonsToyCarTest.java
Labels: x:size/small

#2491 Update log levels to use test runner v3 features
  exercises/concept/log-levels/build.gradle
  exercises/concept/log-levels/src/test/java/LogLevelsTest.java
Labels: x:size/small

#2492 Update salary calculator to use test runner v3 features
  exercises/concept/salary-calculator/build.gradle
  exercises/concept/salary-calculator/src/test/java/SalaryCalculatorTest.java
Labels: x:size/small

#2467 Sync tests for practice exercise `allergies`
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/.meta/version
  exercises/practice/allergies/src/test/java/AllergiesTest.java
Labels: x:size/small

#2493 Update karl's languages to use test runner v3 features
  exercises/concept/karls-languages/build.gradle
  exercises/concept/karls-languages/src/test/java/LanguageListTest.java
Labels: x:size/small

#2494 Use AssertJ for exceptions
  exercises/practice/error-handling/src/test/java/ErrorHandlingTest.java
Labels: x:size/small

#2499 Update wizards and warriors to use test runner v3 features
  exercises/concept/wizards-and-warriors/build.gradle
  exercises/concept/wizards-and-warriors/src/test/java/FighterTest.java
Labels: x:size/small

#2500 Update need for speed to use test runner v3 features
  exercises/concept/need-for-speed/build.gradle
  exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
Labels: x:size/small

#2498 Update squeaky clean to use test runner v3 features
  exercises/concept/squeaky-clean/build.gradle
  exercises/concept/squeaky-clean/src/test/java/SqueakyCleanTest.java
Labels: x:size/small

#2497 Add test-summary action for Gradle tests
  .github/workflows/gradle.yml
Labels: ci

#2504 Update annalyns infiltration to use test runner v3 features
  exercises/concept/annalyns-infiltration/build.gradle
  exercises/concept/annalyns-infiltration/src/test/java/AnnalynsInfiltrationTest.java
Labels: x:size/small

#2503 Update remote control competition to use test runner v3 features
  exercises/concept/remote-control-competition/build.gradle
  exercises/concept/remote-control-competition/src/test/java/RemoteControlCarTest.java
Labels: x:size/small
