Repository exercism/java, pull requests merged in 2024-07, with the labels that each got.

#2817 resistor-color: sync
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#2818 resistor-color-duo: sync
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny

#2819 resistor-color-trio: sync
  exercises/practice/resistor-color-trio/.docs/instructions.md
Labels: x:size/tiny

#2820 Sync docs and a couple of tests
  exercises/practice/affine-cipher/.docs/instructions.md
  exercises/practice/bank-account/.docs/instructions.md
  exercises/practice/change/.meta/tests.toml
  exercises/practice/change/src/test/java/ChangeCalculatorTest.java
  exercises/practice/custom-set/.meta/tests.toml
  exercises/practice/custom-set/src/test/java/CustomSetTest.java
  exercises/practice/go-counting/.docs/instructions.md
  exercises/practice/killer-sudoku-helper/.docs/instructions.md
  exercises/practice/pascals-triangle/.docs/instructions.md
  exercises/practice/pascals-triangle/.docs/introduction.md
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/poker/.docs/instructions.md
  exercises/practice/protein-translation/.meta/tests.toml
  exercises/practice/protein-translation/src/test/java/ProteinTranslatorTest.java
  exercises/practice/queen-attack/.meta/tests.toml
  exercises/practice/queen-attack/src/test/java/QueenAttackCalculatorTest.java
  exercises/practice/roman-numerals/.meta/tests.toml
  exercises/practice/roman-numerals/src/test/java/RomanNumeralsTest.java
  exercises/practice/sublist/.meta/tests.toml
  exercises/practice/sublist/src/test/java/RelationshipComputerTest.java
  exercises/practice/zebra-puzzle/.docs/instructions.md
  exercises/practice/zebra-puzzle/.docs/introduction.md
Labels: x:size/medium

#2822 Rename tryFinishTrack to canFinishRace for better expectations
  exercises/concept/need-for-speed/.docs/instructions.md
  exercises/concept/need-for-speed/.meta/design.md
  exercises/concept/need-for-speed/.meta/src/reference/java/NeedForSpeed.java
  exercises/concept/need-for-speed/src/main/java/NeedForSpeed.java
  exercises/concept/need-for-speed/src/test/java/NeedForSpeedTest.java
Labels: x:size/small

#2826 Cook your lasagna update to title-case
  config.json
Labels: x:size/tiny

#2825 Move Signal.java to "solution" file in Secret Handshake
  exercises/practice/secret-handshake/.meta/config.json
Labels: x:size/tiny
