Repository exercism/java, pull requests merged in 2024-02, with the labels that each got.

#2703 Update README.md
  README.md
Labels: x:size/tiny

#2706 Sync org wide files
  .github/org-wide-files-config.toml
  .github/workflows/configlet.yml
  .github/workflows/no-important-files-changed.yml
Labels: x:size/tiny

#2707 Creating design.md for ``football match reports``
  exercises/concept/football-match-reports/.meta/design.md
Labels: x:size/small

#2702 Adding analyzer feedback for need for speed concept exercise
  exercises/concept/need-for-speed/.meta/design.md
  exercises/concept/need-for-speed/.meta/src/reference/java/NeedForSpeed.java
Labels: x:size/small

#2716 `pop-count`: rename to `eliuds-eggs`
  config.json
  exercises/practice/eliuds-eggs/.docs/instructions.md
  exercises/practice/eliuds-eggs/.docs/introduction.md
  exercises/practice/eliuds-eggs/.meta/config.json
  exercises/practice/eliuds-eggs/.meta/src/reference/java/EliudsEggs.java
  exercises/practice/eliuds-eggs/.meta/tests.toml
  exercises/practice/eliuds-eggs/build.gradle
  exercises/practice/eliuds-eggs/gradle/wrapper/gradle-wrapper.jar
  exercises/practice/eliuds-eggs/gradle/wrapper/gradle-wrapper.properties
  exercises/practice/eliuds-eggs/gradlew
  exercises/practice/eliuds-eggs/gradlew.bat
  exercises/practice/eliuds-eggs/src/main/java/EliudsEggs.java
  exercises/practice/eliuds-eggs/src/test/java/EliudsEggsTest.java
  exercises/settings.gradle
Labels: x:size/tiny

#2709 Update dependabot.yml
  .github/dependabot.yml
Labels: x:size/tiny

#2717 Add documentation on representations
  exercises/shared/.docs/representations.md
Labels: x:size/small

#2724 roman-numerals: sync
  exercises/practice/roman-numerals/.docs/instructions.md
  exercises/practice/roman-numerals/.docs/introduction.md
  exercises/practice/roman-numerals/.meta/config.json
Labels: x:size/tiny

#2727 Adding analyzer feedback for Squeaky Clean concept exercise
  exercises/concept/squeaky-clean/.docs/hints.md
  exercises/concept/squeaky-clean/.meta/design.md
  exercises/concept/squeaky-clean/.meta/src/reference/java/SqueakyClean.java
Labels: x:size/small

#2722 Adding analyzer feedback for karls language concept exercise
  config.json
  exercises/concept/karls-languages/.docs/hints.md
  exercises/concept/karls-languages/.meta/design.md
  exercises/concept/karls-languages/.meta/src/reference/java/LanguageList.java
Labels: x:size/small

#2730 Updating Actionables for the concept exercise Need for Speed
  exercises/concept/need-for-speed/.meta/design.md
Labels: x:size/tiny

#2729 Reformat concept exercise Wizards and Warriors
  concepts/inheritance/introduction.md
  config.json
  exercises/concept/wizards-and-warriors/.docs/hints.md
  exercises/concept/wizards-and-warriors/.docs/instructions.md
  exercises/concept/wizards-and-warriors/.docs/introduction.md
  exercises/concept/wizards-and-warriors/.meta/config.json
  exercises/concept/wizards-and-warriors/.meta/design.md
  exercises/concept/wizards-and-warriors/.meta/src/reference/java/Fighter.java
  exercises/concept/wizards-and-warriors/src/main/java/Fighter.java
  exercises/concept/wizards-and-warriors/src/test/java/FighterTest.java
  exercises/concept/wizards-and-warriors/src/test/java/ReflectionProxy.java
  exercises/concept/wizards-and-warriors/src/test/java/WarriorProxy.java
  exercises/concept/wizards-and-warriors/src/test/java/WizardProxy.java
Labels: x:size/medium

#2733 Updating class message to correct one for ``elons-toy-car`` and ``bird-watcher``
  exercises/concept/bird-watcher/src/main/java/BirdWatcher.java
  exercises/concept/elons-toy-car/src/main/java/ElonsToyCar.java
Labels: x:size/small

#2735 Updating ``lasagna`` and ``wizards-and-warriors-2`` to use directly invokemethod
  exercises/concept/lasagna/src/test/java/utils/Lasagna.java
  exercises/concept/wizards-and-warriors-2/src/test/java/GameMasterProxy.java
Labels: x:size/small

#2739 Updating prefer string concatenation comment for ``Two Fer``
  exercises/practice/two-fer/.meta/design.md
Labels: x:size/tiny

#2742 Adding analyzer feedback for ``wizards-and-warriors-2`` concept exercise
  exercises/concept/wizards-and-warriors-2/.meta/design.md
Labels: x:size/small

#2736 Adding analyzer feedback for ``secrets`` concept exercise
  exercises/concept/secrets/.meta/design.md
Labels: x:size/small
