Repository exercism/java, pull requests merged in 2024-11, with the labels that each got.

#2855 improve explanation on Java array .length property
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  exercises/concept/bird-watcher/.docs/introduction.md
Labels: x:rep/small

#2854 Adding contributor for Complex-Number exercise
  exercises/practice/complex-numbers/.meta/config.json
Labels: x:size/tiny

#2843 Remove collection from array description
  concepts/arrays/about.md
  concepts/arrays/introduction.md
  exercises/concept/bird-watcher/.docs/introduction.md
Labels: x:size/small

#2864 Sync Yacht with problem-specification
  exercises/practice/yacht/.meta/config.json
Labels: x:size/tiny

#2870 Updating tests of Bob exercise to sync with the Problem-Specification repo
  exercises/practice/bob/.meta/config.json
  exercises/practice/bob/.meta/tests.toml
  exercises/practice/bob/src/test/java/BobTest.java
Labels: x:size/small

#2873 Updating tests of Zipper exercise to sync with the Problem-Specification repo
  exercises/practice/zipper/.meta/config.json
  exercises/practice/zipper/.meta/tests.toml
  exercises/practice/zipper/src/test/java/ZipperTest.java
Labels: x:size/small

#2869 Sync file paths, metadata, and documentation with the problem-specifications repository
  exercises/practice/complex-numbers/.docs/instructions.md
  exercises/practice/dot-dsl/.meta/config.json
  exercises/practice/hamming/.docs/instructions.md
  exercises/practice/hamming/.meta/config.json
  exercises/practice/luhn/.docs/instructions.md
  exercises/practice/pov/.meta/config.json
  exercises/practice/protein-translation/.docs/instructions.md
  exercises/practice/pythagorean-triplet/.meta/config.json
  exercises/practice/rna-transcription/.docs/instructions.md
  exercises/practice/square-root/.docs/instructions.md
  exercises/practice/square-root/.docs/introduction.md
  exercises/practice/state-of-tic-tac-toe/.docs/instructions.md
  exercises/practice/sublist/.docs/instructions.md
Labels: x:size/small
