Repository exercism/java, pull requests merged in 2024-01, with the labels that each got.

#2624 Sync tests for practice exercise ``panagram``
  exercises/practice/pangram/.meta/tests.toml
  exercises/practice/pangram/src/test/java/PangramCheckerTest.java
Labels: x:size/small

#2623 Sync tests for practice exercise ``rational numbers``
  exercises/practice/rational-numbers/.meta/src/reference/java/Rational.java
  exercises/practice/rational-numbers/.meta/tests.toml
  exercises/practice/rational-numbers/src/test/java/RationalTest.java
Labels: x:size/small

#2626 Update contribution guide on concept exercises
  reference/implementing-a-concept-exercise.md
Labels: x:size/small

#2565 concepts: method-overloading
  concepts/method-overloading/.meta/config.json
  concepts/method-overloading/about.md
  concepts/method-overloading/introduction.md
  concepts/method-overloading/links.json
  config.json
  exercises/concept/wizards-and-warriors-2/.docs/hints.md
  exercises/concept/wizards-and-warriors-2/.docs/instructions.md
  exercises/concept/wizards-and-warriors-2/.docs/introduction.md
  exercises/concept/wizards-and-warriors-2/.docs/introduction.md.tpl
  exercises/concept/wizards-and-warriors-2/.meta/config.json
  exercises/concept/wizards-and-warriors-2/.meta/design.md
  exercises/concept/wizards-and-warriors-2/.meta/src/reference/java/Character.java
  exercises/concept/wizards-and-warriors-2/.meta/src/reference/java/Destination.java
  exercises/concept/wizards-and-warriors-2/.meta/src/reference/java/GameMaster.java
  exercises/concept/wizards-and-warriors-2/.meta/src/reference/java/TravelMethod.java
  exercises/concept/wizards-and-warriors-2/build.gradle
  exercises/concept/wizards-and-warriors-2/src/main/java/Character.java
  exercises/concept/wizards-and-warriors-2/src/main/java/Destination.java
  exercises/concept/wizards-and-warriors-2/src/main/java/GameMaster.java
  exercises/concept/wizards-and-warriors-2/src/main/java/TravelMethod.java
  exercises/concept/wizards-and-warriors-2/src/test/java/GameMasterProxy.java
  exercises/concept/wizards-and-warriors-2/src/test/java/GameMasterTest.java
  exercises/concept/wizards-and-warriors-2/src/test/java/ReflectionProxy.java
  exercises/settings.gradle
Labels: x:size/large

#2633 Sync tests for practice exercise ``yacht``
  exercises/practice/yacht/.meta/tests.toml
  exercises/practice/yacht/src/test/java/YachtTest.java
Labels: x:size/small

#2634 Sync tests for practice exercise ``transpose``
  exercises/practice/transpose/.meta/tests.toml
  exercises/practice/transpose/src/test/java/TransposeTest.java
Labels: x:size/small

#2636 Order practice exercises by difficulty
  config.json
Labels: x:size/small

#2641 Sync tests for practice exercise ``series``
  exercises/practice/series/.meta/src/reference/java/Series.java
  exercises/practice/series/.meta/tests.toml
  exercises/practice/series/src/test/java/SeriesTest.java
Labels: x:size/small

#2644 Sync docs and metadata for practice exercises
  exercises/practice/leap/.docs/instructions.md
  exercises/practice/leap/.docs/introduction.md
  exercises/practice/leap/.meta/config.json
  exercises/practice/perfect-numbers/.docs/instructions.md
  exercises/practice/pythagorean-triplet/.meta/config.json
  exercises/practice/queen-attack/.docs/instructions.md
  exercises/practice/rest-api/.docs/instructions.md
  exercises/practice/spiral-matrix/.meta/config.json
  exercises/practice/transpose/.meta/config.json
Labels: x:size/small

#2646 Fix Overflow Typo
  exercises/concept/logs-logs-logs/.docs/instructions.md
Labels: x:size/tiny

#2648 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#2647 Adding ``state of tic tac toe`` practice exercise
  config.json
  exercises/practice/state-of-tic-tac-toe/.docs/instructions.md
  exercises/practice/state-of-tic-tac-toe/.meta/config.json
  exercises/practice/state-of-tic-tac-toe/.meta/src/reference/java/GameState.java
  exercises/practice/state-of-tic-tac-toe/.meta/src/reference/java/StateOfTicTacToe.java
  exercises/practice/state-of-tic-tac-toe/.meta/tests.toml
  exercises/practice/state-of-tic-tac-toe/build.gradle
  exercises/practice/state-of-tic-tac-toe/src/main/java/GameState.java
  exercises/practice/state-of-tic-tac-toe/src/main/java/StateOfTicTacToe.java
  exercises/practice/state-of-tic-tac-toe/src/test/java/StateOfTicTacToeTest.java
  exercises/settings.gradle
Labels: x:size/large

#2649 Add bit manipulation concept
  concepts/bit-manipulation/.meta/config.json
  concepts/bit-manipulation/about.md
  concepts/bit-manipulation/introduction.md
  concepts/bit-manipulation/links.json
  config.json
  exercises/concept/secrets/.docs/hints.md
  exercises/concept/secrets/.docs/instructions.md
  exercises/concept/secrets/.docs/introduction.md
  exercises/concept/secrets/.docs/introduction.md.tpl
  exercises/concept/secrets/.meta/config.json
  exercises/concept/secrets/.meta/design.md
  exercises/concept/secrets/.meta/src/reference/java/Secrets.java
  exercises/concept/secrets/build.gradle
  exercises/concept/secrets/src/main/java/Secrets.java
  exercises/concept/secrets/src/test/java/SecretsTest.java
  exercises/settings.gradle
Labels: x:size/large

#2651 Change exercise name "secrets" to "Secrets"
  config.json
Labels: x:size/tiny

#2652 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#2658 Enable representer and analyzer
  README.md
  config.json
Labels: x:size/small

#2692 Add no important files changed workflow
  .github/workflows/no-important-files-changed.yml
Labels: x:size/small

#2696 lasagna: Update design.md
  exercises/concept/lasagna/.meta/design.md
Labels: x:size/tiny

#2695 Adding analyzer feedback to design.md for bird watcher concept exercise
  exercises/concept/bird-watcher/.meta/design.md
  exercises/concept/bird-watcher/.meta/src/reference/java/BirdWatcher.java
Labels: x:size/small

#2698 Updating design.md for squeaky clean after exercise refactor
  exercises/concept/squeaky-clean/.meta/design.md
Labels: x:size/tiny

#2694 Adding analyzer feedback to design.md for log levels concept exercise
  exercises/concept/log-levels/.meta/design.md
Labels: x:size/small
